library(rvest)
library(dplyr)
link='https://www.icc-cricket.com/rankings/mens/player-rankings/odi/batting'
#path=path_allowed(link)
web=read_html(link)
name=web %>% html_nodes('.rankings-block__banner--name-large , .name a') %>% html_text()
View(name)
team=web %>% html_nodes('.table-body__logo-text , .rankings-block__banner--nationality') %>% html_text()
View(team)
rating=web %>% html_nodes('.rating , .rankings-block__banner--rating') %>% html_text()
View(rating)
imdb.rating=data.frame(name,team,rating)
View(imdb.rating)
write.csv(imdb.rating,'odi rating.csv')